//Sort V1.0, English Word Collector
#include <stdio.h>
#include <stdlib.h>
#include <conio.h>
#include <string.h>
#include <dos.h>
#include <ctype.h>
#include <time.h>

void sort()
{
}
/*
//Sort the record by date order;
	recnew=recl;
	if (recno>1)
	{
		recnow=recl->lrec;
		while (recnow!=NULL)
		{
			if (strcmp(recnew->date,recnow->date)<0)
				recnow=recnow->lrec;
			else
				break;
		}
		if (recnow==recnew->lrec);
		else if (recnow==NULL)
		{
			recnew->nrec=rec1;
			recl=recnew->lrec;
			rec1->lrec=recnew;
			recl->nrec=NULL;
			rec1=recnew;
			recnew->lrec=NULL;
		}
		else
		{
			recnew->nrec=recnow->nrec;
			recnow->nrec=recnew;
			recnew->nrec->lrec=recnew;
			recl=recnew->lrec;
			recl->nrec=NULL;
			recnew->lrec=recnow;
		}
	}
}
*/
