*** Credit
set escape off
set color to GR+/R
clear
@0,1 to 24,78 double

@1,22 say "Appleby Library System Version 2.01r"
@3,3 say "Original System Concept........................................Horace Chan"
@4,3 say "Original design and program....................................Horace Chan"
@5,3 say "Appleby Library System Version.......................................2.01r"
@6,3 say "Version programming.................................Horace Chan, Simon Chu"
@7,3 say "                                                                 Tony Tsai"
@8,3 say "Interface Design...............................................Horace Chan"
@9,3 say "Programmer Director..............................................Simon Chu"
@10,3 say "Art Work.........................................................Simon Chu"
@11,3 say "Original Music and SFX...........................................Simon Chu"
@12,3 say "User instructions................................................Tony Tsai"
@14,3 say "Manual design and layout.........................................Tony Tsai"
@15,3 say "Product Manager..................................................Tony Tsai"
@16,3 say "Testing.............................................Patrick Lui, Cyrus Tse"
@17,3 say "                                               Sally Tang, Sanae Nishimura"
@18,3 say "Special Thanks...........................................Mr. Bill Mitchell" 
@19,3 say "                                                    Bill Gates and VIOLET."
set color to R+/R          
@21,4 say "Luxi-Soft Co. Ltd., 1994. All rights reserved."
@22,4 say "Appleby Library System is a trademark of Luxi-Soft Co."
@23,4 say "Other trademarker are the property of respective holders."
key = 0
do while key = 0
    key = inkey()
enddo

